### ISSUE TITLE
Leave message after upload the localization to the crowdin.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1833]
https://github.com/karaoke-dev/karaoke/blob/master/.github/workflows/crowdin.yml

Guess it will be better to let user able to fill the translation after user touch the file in the `Localisation` folder.

Will leave message like this after upload the localization into crowdin successfully.
```
@Username new localization string has been successfully uploaded to the crowdin.
Go to https://crowdin.com/project/karaoke-dev to fill the translation.
```

[Optional] And add the `translation needed` label for it.

Maybe should leave another message for it if upload failed? Like:
```
New localization string has been successfully uploaded to the crowdin.
You can ignore this message or contact to the developer if you want to translate it now.
```

**Comment by andy840119** [comment]
https://github.com/marketplace/actions/add-pr-comment
Here's the example.
Guess should be the same job.

Note:
1. Seems this action able to leave the message after merged
2. Not really sure if this action able to handle the action error? 


Here's the example to handle the error
```
on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          if: always()
          message: |
            **Howdie!**
          message-failure: |
            Uh oh!

```
